services:
  App\Infrastructure\Notification\E2eFileTransactionalEmailGateway: ~

  App\Application\Notification\TransactionalEmailGateway:
    alias: App\Infrastructure\Notification\E2eFileTransactionalEmailGateway
