name: Privacidad

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  privacidad:
    uses: pl0n3r/factory/.github/workflows/privacidad.yml@68eef82e3b21939143a4cbea23b7df2615534e77
    with:
      kit_ref: 68eef82e3b21939143a4cbea23b7df2615534e77
